CREATE DATABASE IF NOT EXISTS BIBLIOTECA_DB;
USE BIBLIOTECA_DB;

CREATE TABLE LIVROS (
    ID_LIVRO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100),
    AUTORES VARCHAR(200),
    GENEROS VARCHAR(100),
    EDITORA VARCHAR(50),
    END_EDITORA VARCHAR(100),
    PRECO DECIMAL(10,2)
);
