CREATE DATABASE IF NOT EXISTS CINEMA_DB;
USE CINEMA_DB;

CREATE TABLE FILMES (
    ID_FILME INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100),
    DIRETORES VARCHAR(100),
    ATORES VARCHAR(200),
    GENEROS VARCHAR(100),
    PRODUTORA VARCHAR(50)
);
