CREATE DATABASE IF NOT EXISTS JOGOS_DB;
USE JOGOS_DB;

-- CREATE TABLE JOGADORES (
--    ID_JOGADOR INT AUTO_INCREMENT PRIMARY KEY,
--    NOME VARCHAR(100),
--    TELEFONES VARCHAR(100),
--    JOGOS_INSCRITOS VARCHAR(100),
--    CLASSES VARCHAR(50)
--);

CREATE TABLE JOGADORES (
    ID_JOGADOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE TELEFONES (
    ID_TELEFONE INT AUTO_INCREMENT PRIMARY KEY,
    ID_JOGADOR INT,
    TELEFONE VARCHAR(14),
    FOREIGN KEY (ID_JOGADOR) REFERENCES JOGADORES(ID_JOGADOR)
);

CREATE TABLE JOGOS (
    ID_JOGO INT AUTO_INCREMENT PRIMARY KEY,
    ID_JOGADOR INT,
    NOME_JOGO VARCHAR(100) NOT NULL,
    CLASSE VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_JOGADOR) REFERENCES JOGADORES(ID_JOGADOR)
);
    
