CREATE DATABASE IF NOT EXISTS JOGOS_DB;
USE JOGOS_DB;

CREATE TABLE JOGADORES (
    ID_JOGADOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    TELEFONES VARCHAR(100),
    JOGOS_INSCRITOS VARCHAR(100),
    CLASSES VARCHAR(50)
);
