CREATE DATABASE IF NOT EXISTS LOJA_DB;
USE LOJA_DB;

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    CATEGORIA VARCHAR(50),
    PRECO DECIMAL(10,2),
    FORNECEDOR VARCHAR(50),
    END_FORNECEDOR VARCHAR(100)
);
