CREATE DATABASE IF NOT EXISTS LOJAONLINE_DB;
USE LOJAONLINE_DB;

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE VARCHAR(100),
    PRODUTOS VARCHAR(200),
    QUANTIDADES VARCHAR(100),
    PRECO_TOTAL DECIMAL(10,2),
    DATA_PEDIDO DATE
);
