CREATE DATABASE IF NOT EXISTS RESTAURANTES_DB;
USE RESTAURANTES_DB;

CREATE TABLE PRATOS (
    ID_PRATO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    INGREDIENTES VARCHAR(200),
    TIPOS VARCHAR(100),
    PRECO DECIMAL(10,2)
);
